name: Go Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'server/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: go mod download && go mod tidy

    - name: Run tests
      run: go test -v ./internal/...