name: Go Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'server/**'
      - 'gui/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'server/**'
      - 'gui/**'

jobs:
  server-test:
    name: Run Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: go mod download && go mod tidy

    - name: Run tests
      run: go test -v ./internal/...

  gui-test:
    name: Run GUI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gui

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgl1-mesa-dev xorg-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev libxfixes-dev libxrender-dev libx11-dev libxext-dev libxcb1-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev

    - name: Install Go dependencies
      run: go mod download

    - name: Run tests
      env:
        FYNE_SCALE: 1.0
        FYNE_RENDERER: software
      run: |
        xvfb-run --server-args="-screen 0 1024x768x24" -a go test -v -timeout 30s ./...